## Упражнения по библиотеке Numpy

In [2]:
import numpy as np

**1.** Дан случайный массив, поменять знак у элементов, значения которых между 3 и 8

In [4]:
# 
rng = np.random.default_rng()
arr = rng.integers(1, 10, size=10)
print(arr)
arr[(arr > 3) & (arr < 8)] *= -1
print(arr)

[2 5 1 4 7 3 6 8 3 7]
[ 2 -5  1 -4 -7  3 -6  8  3 -7]


**2.** Заменить максимальный элемент случайного массива на 0

In [5]:
# 
arr[arr.argmax()] = 0
print(arr)

[ 2 -5  1 -4 -7  3 -6  0  3 -7]


**3.** Построить прямое произведение массивов (все комбинации с каждым элементом). На вход подается двумерный массив

In [6]:
# 
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    print(arrays)
    shape = map(len, arrays)

    ix = np.indices(shape)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print(cartesian([[1, 2, 4], [6, 7]]))

[array([1, 2, 4]), array([6, 7])]
[[1 6]
 [1 7]
 [2 6]
 [2 7]
 [4 6]
 [4 7]]


**4.** Даны 2 массива A (8x3) и B (2x2). Найти строки в A, которые содержат элементы из каждой строки в B, независимо от порядка элементов в B

In [8]:
# 
rng = np.random.default_rng()
A = rng.integers(0,5,(8,3))
B = rng.integers(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = (C.sum(axis=(1,2,3)) >= B.shape[1]).nonzero()[0]
print(rows)

[0 1 3 5 6 7]


**5.** Дана 10x3 матрица, найти строки из неравных значений (например строка [2,2,3] остается, строка [3,3,3] удаляется)

In [11]:
# 
rng = np.random.default_rng()
Z = rng.integers(0,5,(10,3))
E = np.logical_and.reduce(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(Z)
print(U)

[[4 1 1]
 [3 0 1]
 [4 3 4]
 [4 0 3]
 [2 2 3]
 [3 2 2]
 [0 2 4]
 [1 0 4]
 [1 2 3]
 [0 3 3]]
[[4 1 1]
 [3 0 1]
 [4 3 4]
 [4 0 3]
 [2 2 3]
 [3 2 2]
 [0 2 4]
 [1 0 4]
 [1 2 3]
 [0 3 3]]


**6.** Дан двумерный массив. Удалить те строки, которые повторяются

In [12]:
# 
rng = np.random.default_rng()
Z = rng.integers(0, 2, (6,3))
print(Z)
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)

[[1 0 1]
 [1 1 0]
 [1 0 0]
 [0 0 1]
 [0 1 0]
 [0 0 0]]
[[0 0 0]
 [0 0 1]
 [0 1 0]
 [1 0 0]
 [1 0 1]
 [1 1 0]]


______
______

Для каждой из следующих задач (1-5) нужно привести 2 реализации – одна без использования numpy (cчитайте, что там, где на входе или выходе должны быть numpy array, будут просто списки), а вторая полностью векторизованная с использованием numpy (без использования питоновских циклов/map/list comprehension).


__Замечание 1.__ Можно считать, что все указанные объекты непустые (к примеру, в __задаче 1__ на диагонали матрицы есть ненулевые элементы).

__Замечание 2.__ Для большинства задач решение занимает не больше 1-2 строк.

___

* __Задача 1__: Подсчитать произведение ненулевых элементов на диагонали прямоугольной матрицы.  
 Например, для X = np.array([[1, 0, 1], [2, 0, 2], [3, 0, 3], [4, 4, 4]]) ответ 3.

In [14]:
# numpy
rng = np.random.default_rng()
Z = rng.integers(0, 10, (3, 4))
product = np.prod(np.diagonal(Z)[np.diagonal(Z) != 0])
print(Z)
print(np.diagonal(Z))
print(product)
print()

# python
import random

matrix = [[random.randint(0, 10) for _ in range(4)] for _ in range(3)]
for row in matrix:
    print(row)

diagonal = []
product = 1
for i in range(min(len(matrix), len(matrix[0]))):
    if matrix[i][i] != 0:
        diagonal.append(matrix[i][i])
        product *= matrix[i][i]
print(diagonal)
if len(diagonal) == 0:
    print("No non-zero elements")
else:
    print(product)

[[1 3 0 3]
 [0 3 0 2]
 [4 2 6 7]]
[1 3 6]
18

[9, 6, 6, 5]
[6, 2, 10, 10]
[1, 0, 0, 6]
[9, 2]
18


* __Задача 2__: Даны два вектора x и y. Проверить, задают ли они одно и то же мультимножество.  
  Например, для x = np.array([1, 2, 2, 4]), y = np.array([4, 2, 1, 2]) ответ True.

In [15]:
# numpy
rng = np.random.default_rng()
x = rng.integers(1, 3, size=4)
print(x)
y = rng.integers(1, 3, size=4)
print(y)

print(np.array_equal(np.sort(x), np.sort(y)))
print()

# python
x = [random.randint(1, 3) for _ in range(4)]
print(x)
y = [random.randint(1, 3) for _ in range(4)]
print(y)

print(sorted(x) == sorted(y))

[2 2 2 1]
[2 1 2 1]
False

[1, 1, 1, 3]
[2, 3, 1, 2]
False


* __Задача 3__: Найти максимальный элемент в векторе x среди элементов, перед которыми стоит ноль. 
 Например, для x = np.array([6, 2, 0, 3, 0, 0, 5, 7, 0]) ответ 5.

In [16]:
# numpy
rng = np.random.default_rng()
x = rng.integers(0, 10, size=10)
elements_preceded_by_zero = x[np.where(x[:-1] == 0)[0] + 1]
if elements_preceded_by_zero.size > 0:
    max_element = np.max(elements_preceded_by_zero)
else:
    max_element = None  
print(max_element)
print()

# python
x = [random.randint(0, 10) for _ in range(10)]
print(x)
max_element = min(x)
count = 0
for i in range(len(x)-1):
    if (x[i] == 0) and (x[i+1] > max_element):
        max_element =  x[i+1]
        count += 1
if count == 0:
    print("No elements preceded by zero")
else:
    print(max_element)

9

[10, 4, 9, 6, 3, 3, 8, 8, 8, 5]
No elements preceded by zero


* __Задача 4__: Реализовать кодирование длин серий (Run-length encoding). Для некоторого вектора x необходимо вернуть кортеж из двух векторов одинаковой длины. Первый содержит числа, а второй - сколько раз их нужно повторить.  
 Например, для x = np.array([2, 2, 2, 3, 3, 3, 5]) ответ (np.array([2, 3, 5]), np.array([3, 3, 1])).

In [17]:
# numpy
x = np.array([2,2,2,3,3,3,5])
tuple_of_vectors = (np.unique_counts(x).values, np.unique_counts(x).counts)
print(tuple_of_vectors)
print()

# python
x = [2,2,2,3,3,3,5]
dict = {}
for i in x:
    if i in dict:
        dict[i] += 1
    else:
        dict[i] = 1

print((list(dict.keys()), list(dict.values())))

(array([2, 3, 5]), array([3, 3, 1]))

([2, 3, 5], [3, 3, 1])


* __Задача 5__: Даны две выборки объектов - X и Y. Вычислить матрицу евклидовых расстояний между объектами. Сравните с функцией scipy.spatial.distance.cdist по скорости работы.

In [19]:
# numpy
from scipy.spatial import distance
import timeit

X = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
Y = np.array([[1, 1, 1], [2, 2, 2], [3, 3, 3]])

distance_matrix = np.linalg.norm(X[:, np.newaxis] - Y, axis=2)
print("Distance Matrix (numpy):")
print(distance_matrix)
print()

# Compare with scipy

def measure_np():
    distance_matrix = np.linalg.norm(X[:, np.newaxis] - Y, axis=2)
    return distance_matrix

def measure_scipy():
    distance_matrix_scipy = np.zeros((len(X), len(Y)))
    for i in range(len(X)):
        for j in range(len(Y)):
            distance_matrix_scipy[i, j] = distance.euclidean(X[i], Y[j])
    
    return distance_matrix_scipy

# Measure time for np.linalg.norm
time_np = timeit.timeit(measure_np, number=100000)
print(f"np.linalg.norm: Time taken for 100000 runs: {time_np} seconds")

# Measure time for scipy.spatial.distance.euclidean
time_scipy = timeit.timeit(measure_scipy, number=100000)
print(f"scipy.spatial.distance.euclidean: Time taken for 100000 runs: {time_scipy} seconds")
print()
# python
import math

X = [[1, 2, 3], [4, 5, 6], [7, 8, 9]]
Y = [[1, 1, 1], [2, 2, 2], [3, 3, 3]]

def euclidean_distance(point1, point2):
    return math.sqrt(sum((p1 - p2) ** 2 for p1, p2 in zip(point1, point2)))

def measure_py():
    distance_matrix_py = [[0 for _ in range(len(Y))] for _ in range(len(X))]
    for i in range(len(X)):
        for j in range(len(Y)):
            distance_matrix_py[i][j] = euclidean_distance(X[i], Y[j])
    
    return distance_matrix_py

distance_matrix_py = measure_py()
print("Distance Matrix (python):")
for row in distance_matrix_py:
    print(row)

# Measure time for python
time_py = timeit.timeit(measure_py, number=100000)
print(f"just.python: Time taken for 100000 runs: {time_py} seconds")

# Numpy значительно лучше по скорости работы по сравнению с scipy (быстрее примерно в 6.5 раз)
# На обычном питоне скорость только немного ниже numpy (примерно в 1.2 раза)

Distance Matrix (numpy):
[[ 2.23606798  1.41421356  2.23606798]
 [ 7.07106781  5.38516481  3.74165739]
 [12.20655562 10.48808848  8.77496439]]

np.linalg.norm: Time taken for 100000 runs: 0.6121405999874696 seconds
scipy.spatial.distance.euclidean: Time taken for 100000 runs: 3.949999400007073 seconds

Distance Matrix (python):
[2.23606797749979, 1.4142135623730951, 2.23606797749979]
[7.0710678118654755, 5.385164807134504, 3.7416573867739413]
[12.206555615733702, 10.488088481701515, 8.774964387392123]
just.python: Time taken for 100000 runs: 0.688436600001296 seconds


_______
________

* #### __Задача 6__: CrunchieMunchies __*__

Вы работаете в отделе маркетинга пищевой компании MyCrunch, которая разрабатывает новый вид вкусных, полезных злаков под названием **CrunchieMunchies**.

Вы хотите продемонстрировать потребителям, насколько полезны ваши хлопья по сравнению с другими ведущими брендами, поэтому вы собрали данные о питании нескольких разных конкурентов.

Ваша задача - использовать вычисления Numpy для анализа этих данных и доказать, что ваши **СrunchieMunchies** - самый здоровый выбор для потребителей.


In [20]:
import numpy as np

1. Просмотрите файл cereal.csv. Этот файл содержит количества калорий для различных марок хлопьев. Загрузите данные из файла и сохраните их как calorie_stats.

In [21]:
calorie_stats = np.loadtxt("./data/cereal.csv", delimiter=",")
calorie_stats

array([ 70., 120.,  70.,  50., 110., 110., 110., 130.,  90.,  90., 120.,
       110., 120., 110., 110., 110., 100., 110., 110., 110., 100., 110.,
       100., 100., 110., 110., 100., 120., 120., 110., 100., 110., 100.,
       110., 120., 120., 110., 110., 110., 140., 110., 100., 110., 100.,
       150., 150., 160., 100., 120., 140.,  90., 130., 120., 100.,  50.,
        50., 100., 100., 120., 100.,  90., 110., 110.,  80.,  90.,  90.,
       110., 110.,  90., 110., 140., 100., 110., 110., 100., 100., 110.])

2. В одной порции CrunchieMunchies содержится 60 калорий. Насколько выше среднее количество калорий у ваших конкурентов?

Сохраните ответ в переменной average_calories и распечатайте переменную в терминале

In [22]:
# 106.88
average_calories = np.mean(calorie_stats)
print(average_calories)

106.88311688311688


3. Корректно ли среднее количество калорий отражает распределение набора данных? Давайте отсортируем данные и посмотрим.

Отсортируйте данные и сохраните результат в переменной calorie_stats_sorted. Распечатайте отсортированную информацию

In [23]:
# 
calorie_stats_sorted = np.sort(calorie_stats)
print(calorie_stats_sorted)

[ 50.  50.  50.  70.  70.  80.  90.  90.  90.  90.  90.  90.  90. 100.
 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100. 100.
 100. 100. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110.
 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110. 110.
 110. 110. 110. 120. 120. 120. 120. 120. 120. 120. 120. 120. 120. 130.
 130. 140. 140. 140. 150. 150. 160.]


4. Похоже, что большинство значений выше среднего. Давайте посмотрим, является ли медиана наиболее корректным показателем набора данных.

Вычислите медиану набора данных и сохраните свой ответ в median_calories. Выведите медиану, чтобы вы могли видеть, как она сравнивается со средним значением.

In [24]:
# 110.0
median_calories = np.median(calorie_stats)
print(median_calories)

110.0


5. В то время как медиана показывает, что по крайней мере половина наших значений составляет более 100 калорий, было бы более впечатляюще показать, что значительная часть конкурентов имеет более высокое количество калорий, чем CrunchieMunchies.

Рассчитайте различные процентили и распечатайте их, пока не найдете наименьший процентиль, превышающий 60 калорий. Сохраните это значение в переменной nth_percentile.

In [25]:
# 4th_percentile = 70 (3d = 55.6)
print("50th percentile: ",
      np.percentile(calorie_stats, 50))
print("25th percentile: ",
      np.percentile(calorie_stats, 25))
print("10th percentile: ",
      np.percentile(calorie_stats, 10))
print("5th percentile: ",
      np.percentile(calorie_stats, 5))
print("4th percentile: ",
      np.percentile(calorie_stats, 4))
print("3th percentile: ",
      np.percentile(calorie_stats, 3))

nth_percentile = np.percentile(calorie_stats, 4)

50th percentile:  110.0
25th percentile:  100.0
10th percentile:  90.0
5th percentile:  70.0
4th percentile:  70.0
3th percentile:  55.599999999999994


6. Хотя процентиль показывает нам, что у большинства конкурентов количество калорий намного выше, это неудобная концепция для использования в маркетинговых материалах.

Вместо этого давайте подсчитаем процент хлопьев, в которых содержится более 60 калорий на порцию. Сохраните свой ответ в переменной more_calories и распечатайте его

In [26]:
# 96.1
more_calories = (np.sum(calorie_stats > 60) / len(calorie_stats)) * 100
print(more_calories)

96.1038961038961


7. Это действительно высокий процент. Это будет очень полезно, когда мы будем продвигать CrunchieMunchies. Но один вопрос заключается в том, насколько велики различия в наборе данных? Можем ли мы сделать обобщение, что в большинстве злаков содержится около 100 калорий или разброс еще больше?

Рассчитайте величину отклонения, найдя стандартное отклонение, Сохраните свой ответ в calorie_std и распечатайте на терминале. Как мы можем включить эту ценность в наш анализ?

In [27]:
# 19.36
calorie_std = np.std(calorie_stats)
print(calorie_std)

# Percentage of cereals within one standard deviation of the mean
within_one_std = np.sum((calorie_stats >= (average_calories - calorie_std)) & (calorie_stats <= (average_calories + calorie_std)))
percentage_within_one_std = (within_one_std / len(calorie_stats)) * 100

print(f"Percentage of cereals within one standard deviation of the mean: {percentage_within_one_std:.2f}%")

19.35718533390827
Percentage of cereals within one standard deviation of the mean: 81.82%


8. Напишите короткий абзац, в котором кратко изложите свои выводы и то, как, по вашему мнению, эти данные могут быть использованы в интересах Mycrunch при маркетинге CrunchieMunchies.

In [167]:
# 
Стандартное отклонение (19.36) можно считать умеренным для данного среднего значения (106.9). 
Поскольку процент хлопьев в пределах одного стандартного отклонения довольно высокий (percentage_within_one_std, 81.82%), можно сделать вывод, что да, большинство хлопьев содержит около 100 калорий.

Данное обобщение можно использовать в интересах компании. 
Также можно использовать среднее (как более понятное потребителям по сравнению с медианой) и процент хлопьев с содержанием калорий более 60 (96.1%).

Все эти показатели однозначно говорят о том, что по низкой калорийности хлопья компании превосходят большинство конкурентов.